update: zombie comment when someone liked
givery-bootcamp/dena-2024-team5 pull request #104
Opened 2024-06-25 08:49 UTC by txxxxc

solve #88

2024-06-25 08:55 UTC, hasegawa282 commented on backend/internal/repository/user.go
> +	err := p.Conn.Debug().Where("name like ?", "%zombie%").Order("RAND()").First(&user).Error
このDebug()って消した方が良さそう?

2024-06-25 08:55 UTC, hasegawa282 commented on backend/internal/controller/post_like_add.go
> +	log.Println("commented zombie")
このlogも消した方が良さそう！

2024-06-26 02:33 UTC, uga-rosa requested changes

2024-06-26 02:33 UTC, uga-rosa commented on backend/internal/repository/user.go
> +	err := p.Conn.Where("name like ?", "%zombie%").Order("RAND()").First(&user).Error
このlikeは雑すぎるかなあ
ユーザーがzombieって文字列含む名前を使ったら、そのユーザーのアカウントを勝手に使ってしまう

2024-06-26 04:28 UTC, uga-rosa approved these changes

2024-06-26 04:45 UTC, merged