Feat/#24 signin user api
givery-bootcamp/dena-2024-team5 pull request #48
Opened 2024-06-17 08:34 UTC by txxxxc

# やったこと

ログインしているユーザーの情報を取るAPIを作成しました。

2024-06-17 08:41 UTC, uga-rosa commented on backend/internal/interfaces/user_repository.go
> +	GetDetail(id int) (*entities.User, error)
idはuintじゃね？

2024-06-17 08:42 UTC, uga-rosa commented on backend/internal/middleware/router.go
> +
空行

2024-06-17 08:43 UTC, uga-rosa commented on backend/internal/middleware/jwt-authorize.go
> +	UserID int `json:"user_id,omitempty"`
ここもuint

2024-06-17 08:47 UTC, uga-rosa requested changes

2024-06-17 08:47 UTC, uga-rosa commented on backend/internal/middleware/jwt-authorize.go
> +			})
controller_helperのhandleError使った方が良い
エラー時のbodyの型も保証したい

2024-06-17 08:47 UTC, uga-rosa commented on backend/internal/middleware/jwt-authorize.go
> +			})
ここも

2024-06-17 08:47 UTC, uga-rosa commented on backend/internal/middleware/jwt-authorize.go
> +			ctx.AbortWithStatusJSON(http.StatusInternalServerError, errors.New("invalid token"))
ここも

2024-06-17 08:47 UTC, uga-rosa commented on backend/internal/middleware/jwt-authorize.go
> +
空行

2024-06-17 08:47 UTC, uga-rosa commented on backend/internal/repositories/user_repository.go
> +func (p *UserRepository) GetDetail(id int) (*entities.User, error) {
uint

2024-06-17 09:07 UTC, uga-rosa commented on backend/internal/middleware/jwt-authorize.go
> +			ctx.AbortWithStatusJSON(http.StatusInternalServerError, errors.New("invalid token"))
ここgin.Hの危険性ちゃんと出てるんだよね。
他の2箇所と第二引数の型が違ってる。。。

このファイル内でErrorResponse使うヘルパー関数作って使うようにしてほしい！
```go
func handleError(ctx *gin.Context, status int, err error) {
	res := ErrorResponse{
		Message: err.Error(),
	}
	ctx.AbortWithStatusJSON(status, &res)
}
```

controllerへの依存が良くないならErrorResponseはinterfaceに動かす方がいいかも

2024-06-18 02:44 UTC, txxxxc commented on backend/internal/controllers/user_get_me.go
> +// @Router	/user/me	[get]
[764c13b](https://github.com/givery-bootcamp/dena-2024-team5/pull/48/commits/764c13b117abd6958417731d7dcf933b62841ef3)で修正しました！

2024-06-18 02:52 UTC, uga-rosa commented on backend/internal/controllers/user_get_me.go
> +// @Accept	json
GETだとbodyないからaccept書かなくてよさそう

https://github.com/swaggo/swag?tab=readme-ov-file#general-api-info

2024-06-18 02:54 UTC, hasegawa282 approved these changes

2024-06-18 02:54 UTC, uga-rosa approved these changes

2024-06-18 02:55 UTC, merged